# SPDX-FileCopyrightText: 2026 Quantile Labs
# SPDX-License-Identifier: Apache-2.0

"""Enforce a pack's declared egress allowlist with a proxy sidecar.

02-DESIGN.md section 7. A pack declares the hosts it needs in its manifest, `freeze` pins
that list into the lock, and this module is what makes the list a control rather than a
description.

The shape is two networks and one proxy. The pack runs on a Docker network created
`--internal`, which has no route off the host at all. The proxy sits on that network and
is separately attached to the default bridge, so it is the only way out. The pack is told
about it through `HTTPS_PROXY`, and **containment does not depend on the pack honouring
that**: a pack that ignores the variable, or that was written to ignore it, is on a
network with nowhere to go. Environment variables are how the pack is asked politely; the
internal network is what makes the answer irrelevant.

The proxy allowlists by `CONNECT` host and never terminates TLS. It sees the hostname in
the CONNECT line and the bytes stay opaque. A proxy that decrypted traffic would be a
proxy that had to be trusted with the client's API keys, and no bank's security review
should approve one. That constraint is the point, not a limitation.
"""

import re
import shlex

HOST = re.compile(
    r"^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?(\.[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?)+$",
    re.IGNORECASE,
)
"""A hostname and nothing else. No scheme, no port, no path, no wildcard.

This is a security boundary, not tidiness. Every declared host is written into a squid
configuration file, so a host of `example.com\\nhttp_access allow all` would append a rule
that grants everything. The allowlist comes from a pack's manifest, and a pack is the
thing being contained.
"""

PROXY_IMAGE = "ubuntu/squid:latest"
"""Canonical's build. Named here rather than in a plan because it is part of the trust
boundary rather than part of the experiment, and the digest that actually ran is recorded
in `environment.json`."""

PROXY_PORT = 3128

PROXY_MEMORY_MB = 512
PROXY_PIDS = 128
"""The sidecar is a container this tool starts, so it runs under a ceiling like any
other. Squid with caching denied needs very little; 512 is chosen to leave room for the
image's own startup rather than because squid asks for it."""
PROXY_ALIAS = "egress"
"""What the pack resolves. Docker's embedded DNS answers it on the internal network, which
is the only name resolution a contained pack gets."""

ACCESS_LOG = "/var/log/squid/access.log"
"""Where the image's own entrypoint tails from. Squid drops privileges to user `proxy`
before opening its logs, so `stdio:/dev/stdout` fails with a fatal error that reads like a
permissions bug. See store.md."""


ADDRESS = re.compile(r"^[0-9.]+$")
"""A bare IPv4 address. `dstdomain` matches names, not addresses, so squid would accept the
configuration and then match nothing. That fails closed, which is right, and gives the pack
author a denial with no explanation, which is not. Refused here with a reason instead."""


def check_hosts(hosts: list[str]) -> list[str]:
    """The declared hosts that are not usable hostnames. Empty means all of them are."""
    return [host for host in hosts if ADDRESS.match(host) or not HOST.match(host)]


def squid_config(hosts: list[str]) -> str:
    """A default-deny configuration allowing CONNECT to exactly these hosts.

    `dstdomain example.com` matches that host and not its subdomains: a leading dot is
    what widens it, and a pack that needs a subdomain declares the subdomain.
    """
    rejected = check_hosts(hosts)
    if rejected:
        raise ValueError(f"not hostnames: {', '.join(rejected)}")

    # DNS is case insensitive and squid's acl is not, so the name is normalised once here
    # rather than a pack author being told API.openai.com is not a hostname.
    declared = "\n".join(f"acl declared dstdomain {host.lower()}" for host in hosts)
    return f"""# Generated by Touchstone. Every line is derived from the pack's manifest.
http_port {PROXY_PORT}

{declared}

acl SSL_ports port 443
acl Safe_ports port 80 443
acl CONNECT method CONNECT

# Default deny. The allow sits between two denies on purpose: a rule appended after this
# block by anything other than this generator still cannot widen the allowlist.
http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports
http_access allow declared
http_access deny all

# The pack's network is internal, so the proxy resolves names and the pack never does.
dns_nameservers 1.1.1.1 8.8.8.8

cache deny all
access_log stdio:{ACCESS_LOG}
"""


def proxy_env(alias: str = PROXY_ALIAS, port: int = PROXY_PORT) -> dict[str, str]:
    """What the pack is told, in the spellings the common HTTP clients read."""
    url = f"http://{alias}:{port}"
    return {
        "HTTP_PROXY": url,
        "HTTPS_PROXY": url,
        "http_proxy": url,
        "https_proxy": url,
        "NO_PROXY": "",
        "no_proxy": "",
    }


CONFIG_PATH = "/etc/squid/squid.conf"
ENTRYPOINT = "/usr/local/bin/entrypoint.sh"
"""The image's own launcher. It tails the squid logs to stdout, which is how the access
log reaches `docker logs` and from there the bundle."""

READY = "Accepting HTTP Socket connections"
"""What squid prints once it is listening. Roughly four seconds after start, so a run that
does not wait for it races the pack's first request."""


def start_command(config: str) -> str:
    """Write the configuration inside the container, then hand over to squid.

    Bind mounting the file works, and is not used. It would need a host path that outlives
    this call and lies inside a directory Docker Desktop is configured to share, and a
    temporary directory on macOS is not shared by default. Writing the bytes through the
    container's own shell depends on nothing outside Docker.
    """
    written = f"printf %s {shlex.quote(config)} > {shlex.quote(CONFIG_PATH)}"
    return f"{written}; exec {ENTRYPOINT} -f {CONFIG_PATH} -NYC"
